# Generated by Django 4.0.1 on 2022-02-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_token',
            field=models.CharField(default='a', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='refresh_token',
            field=models.CharField(default='a', max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='extra_data',
            field=models.JSONField(default=dict),
        ),
    ]
