# Generated by Django 4.0.1 on 2022-02-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0010_alter_user_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jwt',
            field=models.CharField(default='F', max_length=512),
            preserve_default=False,
        ),
    ]
