# Generated by Django 4.0.1 on 2022-03-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0012_alter_user_options_alter_user_refresh_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=50)),
                ('auth_url', models.CharField(max_length=256)),
                ('client_secret', models.CharField(max_length=256)),
                ('client_id', models.CharField(max_length=256)),
                ('redirect_uri', models.CharField(max_length=256)),
                ('scope', models.CharField(blank=True, max_length=256)),
            ],
        ),
    ]
