# Generated by Django 4.0.1 on 2022-03-14 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0013_providers'),
    ]

    operations = [
        migrations.AddField(
            model_name='providers',
            name='state',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
