# Generated by Django 4.0.1 on 2022-03-14 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0015_providers_acess_type_providers_response_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='providers',
            old_name='acess_type',
            new_name='access_type',
        ),
    ]
